[project]
name = "user-guide"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi",
]

[tool.uv.sources]
fastapi = { workspace = true }

[tool.uv.workspace]
members = [
    "path_parameter",
]
